workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      groups:
        - google_play
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$HOME/programs/android/sdk" > local.properties
      - name: Generate gradlew
        script: |
          flutter pub get
          flutter build apk --debug
      - name: Build Android app
        script: |
          cd android && ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - dmpcsaad3@gmail.com